### ISSUE TITLE
Switches not functioning in FASA Apollo CM

### ISSUE THREAD

**Issue by Sam-Neale** [MOARdV/MOARdVPlus#2]
The switches are not functioning and sas sync shows error despite not being on.
[KSP.log.zip](https://github.com/MOARdV/MOARdVPlus/files/4091034/KSP.log.zip)

**Comment by MOARdV** [comment]
It looks like you've got FASA installed.  I think the issue is that the MAS IVA has the same name as the FASA IVA.  It's not supposed to, but I probably overlooked that at the time.  What I suspect is happening is that the MAS IVA is inserting itself into the FASA pod, but the FASA pod isn't configured to support it.

When you added the CM in the VAB, did you select the "MAS FASA RA-01 CM"?

**Comment by Sam-Neale** [comment]
No it appears I did not

**Comment by Sam-Neale** [comment]
Thats MASA FASA RA-01CM seems to fix it

**Comment by Sam-Neale** [comment]
I question (unrelated) with the tower jet switch, is there a action group that should be assigned to the jet? Cause I am using the fasa launch escape tower and cover but it doesn't do anything.

**Comment by MOARdV** [comment]
> No it appears I did not

Okay, I'll need to update the MAS IVA to use a different name.

> I question (unrelated) with the tower jet switch, is there a action group that should be assigned to the jet?

The IVA was designed for use with Bluedog Design Bureau's Kane / Sarnus parts, so all of the special switches work only with BDB.  It would require a number of edits to the IVA config files to add support for FASA as well.
